#!/bin/sh
echo "FF0000 Red"
sleep 1
echo "00FF00 Green"
sleep 1
echo "0000FF Blue"
sleep 1
echo "FFFF00:circle.svg Circle"
sleep 1
echo "FF00FF:cube.svg Cube"
sleep 1
echo "00FFFF:'twin moons.svg' Twin moons"
sleep 1
