#!/bin/bash

# Copyright 2016 Marcelo Garlet Millani

# This file is part of itsalamp.

# itsalamp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# itsalamp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with itsalamp.  If not, see <http://www.gnu.org/licenses/>.


function help()
{
	echo "usage: $0 <[HOURSh][MINUTESm][SECONDSs]> [ICONS...]"
}

function alarm()
{
	# option to reset the timer. The string 'reset' will be sent to itsacounter
	echo "+'Reset ($TIME)' reset"
	# option to set the timer to a specific value
	#echo "+'10 Minutes' 10m"
	itsacounter $TIME 00FF00 FF9900 ${ICONS[@]} < "$FIFO"

	echo "#FF0000:'$FINAL' Time is up!"
	# notify with a popup
	notify-send -u critical "Time is up!"
	# blink quickly
	for (( i=0 ; i < 10 ; i++ ))
	do
		sleep 0.2
		echo "#FFFFFF Time is up!"
		sleep 0.2
		echo "#FF0000 Time is up!"
	done

	sleep 5
}

TIME=$1

if [[ $# == 0 ]]
then
	help
	return 1
elif [[ $# == 1 ]]
then
	# default animation
	ICONS=(wallclock-t0.svg wallclock-t1.svg wallclock-t2.svg wallclock-t3.svg wallclock-t4.svg)
else
	shift 1
	ICONS=$*
fi

FINAL=${ICONS[${#ICONS[@]} - 1]}
unset ICONS[${#ICONS[@]}-1]

PID=$$
# setup a fifo
mkdir -p /tmp/itsalarm
FIFO=/tmp/itsalarm/fifo."$PID"
# if the fifo already exists, it belonged to a dead process
rm -f "$FIFO"
mkfifo "$FIFO"

alarm | itsalamp > "$FIFO"
rm "$FIFO"
