#!/bin/bash

PDOWN=0
PUP=0

DHIGH=$[ 500  ]
UHIGH=$[ 60 ]

ICON="double-circles.svg"

while [[ 1 ]]
do
	DOWN=0
	UP=0
	while read line
	do
		cols=($line)
		DOWN=$[ $DOWN + ${cols[1]} ]
		UP=$[ $UP + ${cols[9]} ]
	done < <( cat /proc/net/dev | tail -n+3 )
	SD=$[ $DOWN - $PDOWN ]
	SU=$[ $UP - $PUP ]
	# Set a color for upload
	RU=$[ 205 * $SU / $UHIGH + 50 ]
	if [[ $RU -gt 255 ]]
	then
		RU=255
	fi
	# Set a color for download
	RD=$[ 205 * $SD / $DHIGH + 50 ]
	if [[ $RD -gt 255 ]]
	then
		RD=255
	fi
	DC=$(printf "%02x" $RD)
	UC=$(printf "%02x" $RU)
	# convert from bytes to kilobytes per second
	SU=$[ $SU / 1024 ]
	SD=$[ $SD / 1024 ]
	echo "#$UC""$DC""$UC:'$ICON' Up: $SU kB/s\nDown: $SD kB/s"
	PDOWN=$DOWN
	PUP=$UP
	sleep 1
done | itsalamp
